### ISSUE TITLE
support of building:level and building:min_level

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/blender-osm#13]
Tags `building:level` and `building:min_level` should be supported

**Comment by ccamara** [comment]
+1 to this feature.

In case no `building:height` is provided `building:level` could be used to approximate the height by multiplying the number of levels by a number (ideally as a user input on the importer's options)

**Comment by vvoovv** [comment]
I'm going to implement that feature in the coming days

**Comment by vvoovv** [comment]
The basic support for `building:levels` and `building:min_level` has been added. Please try it out.
However a big issue remains. I'll describe it here later

**Comment by vvoovv** [comment]
Here is the description of the remaining issue.

It occurs when both `building` and `building:part` are used.
Take look at this building composed of one `building` tag and two `building:part` tags:
http://www.openstreetmap.org/way/365821302 `building` (6 levels)
http://www.openstreetmap.org/way/365821115 `building:part` (5 levels)
http://www.openstreetmap.org/way/365821209 `building:part` (5 levels)

It must look like this (the central part is one level higher):
![osm_3d_1](https://cloud.githubusercontent.com/assets/613295/18521077/663d7920-7af6-11e6-8aa7-e2cae9ded83d.png)
(image from [opensciencemap.org](http://opensciencemap.org))

However it currently looks like this after import to Blender:
![osm_3d_2](https://cloud.githubusercontent.com/assets/613295/18521340/6de96886-7af7-11e6-951d-dca0223d67be.png)
I.e., there is no central part. I delete the top and a side face of the `building` extrusion for clearness.

I will try to address the problem in the coming days.

**Comment by vvoovv** [comment]
Just to close this issue.

The behavior I described in the previous message is unconventional.  I decided not to process it. The central part of the building must be explicitly mapped as building:part=yes.

So I've completely rewritten the addon to support OSM in 3D. Give it a try.
