### ISSUE TITLE
support for roof* tags

### ISSUE THREAD

**Issue by ccamara** [vvoovv/blender-osm#25]
According to [OSM's wiki on 3D buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Roof), there are some interesting tags regarding to roofs that may be imported as well, as they dramatically affect the final result of the 3D building:
- `roof:shape`  (which can be flat, skillion, gabled, half-hipped, hipped, pyramidal, gambrel, mansard, dome, onion,round, saltbox )
- `roof:orientation`=along/across
- `roof:direction=*`

Additionally, these ones could be considered too:
- `roof:height`
- `roof:angle`

**Comment by vvoovv** [comment]
I'd like to note that creating a hipped roof for an arbitrary polygon isn't an easy task. I started to address the problem in the [BCGA](https://github.com/vvoovv/bcga/wiki/hip_roof) repo.

**Comment by ccamara** [comment]
I am aware that it is not an easy task (I wouldn't even know how to do what you've achieved so far!). Glad to hear that you have started elsewhere, though.

**Comment by stuarta0** [comment]
vvoovv can we use https://github.com/OSMBuildings/OSMBuildings/tree/master/ as a basis for roof calculation?  If you're OK with that I might take a look unless you've progressed it further in the other repo.

**Comment by vvoovv** [comment]
I am rewriting the add-on from scratch, since the current version reached its limits.
Regarding OSMBuildings. It probably calculates roofs fast, but gives incorrect results for complex roof shapes (e.g. L-shape, U-shape, H-shape).

Let's return to this issue in a couple of weeks or so, after I proceed with the new version of the add-on.

**Comment by vvoovv** [comment]
A number of roof shapes is now supported:
flat, pyramidal, skillion, dome, onion

![](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/moscow_kremlin.png)

**Comment by ccamara** [comment]
Glad to hear that, although unfortunately I can't try them now after you have deleted all the contents on this repo :(

**Comment by vvoovv** [comment]
The development is done in the repository with limited access. By buying the addon you support the addon development. I hope the price is affordable for everyone. All customers will get the addon source code.

**Comment by stuarta0** [comment]
I'd say GitHub isn't the place for this code anymore. It should promote community involvement with the development of the codebase. Whilst charging a small fee for it provides some monetary incentive for continued development, it ensures no one else would consider contributing. Plus all the issues in GitHub are just turning into licensing issues rather than actual code issues.

**Comment by vvoovv** [comment]
@stuarta0 
There are incorrect statements in your message.
1) The code is hosted at Github, but in a paid repository with limited access (see https://github.com/pricing)
2) There are already contributors besides me. If you'd like to contribute, lets' discuss it. Send me a message via [e-mail](mailto:prokitektura+support@gmail.com).

In general this thread is to discuss roofs. Please start a separate thread for blaming me :)

**Comment by stuarta0** [comment]
Agreed. I'll take it up in an email.

**Comment by vvoovv** [comment]
I grouped all remaining issues for the upcoming release with support of gabled and round roofs into a [milestone](https://github.com/vvoovv/blender-osm/milestone/1).

**Comment by vvoovv** [comment]
The implementation of 4 more roof shapes is finished.
A large number of roof shapes is supported now:
* flat
* gabled
* hipped (for a quadrangle outline only)
* mono-pitched
* half-hipped
* round
* pyramidal
* gambrel
* dome
* onion
* saltbox

I create a separate issue #52 to track the support of hipped roofs for an arbitrary building outline

**Comment by vvoovv** [comment]
@stuarta0 
Good news!
The source code of the blender-osm addon is back on Github: https://github.com/vvoovv/blender-osm/tree/release
The addon can be also dowloaded for free via Gumroad: https://gumroad.com/l/blender-osm
