### ISSUE TITLE
a more detailed complete map?

### ISSUE THREAD

**Issue by enzyme69** [vvoovv/blender-osm#26]
I tried the latest Add-On, seems like the path extrude is no longer in the option? 

Also, with building, etc, is there a suggestion to get a more hires version of buildings, etc? Wondering how much details of the city we can get using this Add-On?

Is there a good thread or blog displaying the whole process?

**Comment by vvoovv** [comment]
Why do you need to extrude path? I'm rewriting the add-on. There will be an option to separate paths in a separate object.

The current version doesn't process building colors and roofs of the building. It will be implemented in the new version. Besides that there is nothing to add to the level of details.

Here is the related OpenStreetMap specification: http://wiki.openstreetmap.org/wiki/Simple_3D_buildings

**Comment by vvoovv** [comment]
Among the other features I hope to support polygons (and buildings in particular) with holes in the new version of the add-on

**Comment by vvoovv** [comment]
I've completely rewritten the addon to support OSM in 3D to the full extent.
Give it a try.

**Comment by vvoovv** [comment]
Hi @enzyme69,
The source code of the blender-osm addon is back on Github: https://github.com/vvoovv/blender-osm/tree/release
The addon can be also downloaded for free via Gumroad: https://gumroad.com/l/blender-osm
