### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JuniorNayal** [vvoovv/blender-osm#29]
![c](https://cloud.githubusercontent.com/assets/22707126/19212652/57feccda-8d73-11e6-865d-a2f9cd99e889.png)

How to overcome this?
Can Anyone Help Me (Blender version 2.78)

**Comment by vvoovv** [comment]
I hoped you solved the problem yourself.

I just noticed I tried to register a wrong file (Import OpenStreetMap(.osm).py) as OSM addon. 

I've rewritten the addon from scratch.
I might want to try the new version.
