### ISSUE TITLE
Memory leak in OSM importer?

### ISSUE THREAD

**Issue by ersagunkuruca** [vvoovv/blender-osm#32]
Admittedly I am trying to import rather large files from here: https://mapzen.com/data/metro-extracts/

A 200MB OSM file of Sydney - Australia uses 4GB of peak memory and takes too much time. After the import Blender uses only 200MB. So I think there should be some memory leak in the importer. 

Now I don't mind the time, but I want to import New York City OSM (2GB) and it is impossible with this much of a memory usage. (It goes up to 10GB and crashes.)

Any ideas? (I don't have much experience with Python but maybe I can help with development.)

**Comment by vvoovv** [comment]
I am rewriting the add-on from scratch. The new version loads 100 mb OSM file in a minute. The preliminary version (no roofs, no materials) will be published in a couple of weeks.

2Gb is probably to much. Try to cut a smaller area out of the large region.

**Comment by vvoovv** [comment]
Give it a try again. I was able to import an OSM file with the size 350 Mb.
Not sure about 2Gb though.

You might want to give it a try again.
