### ISSUE TITLE
I can't enable the OSM add-on

### ISSUE THREAD

**Issue by Punchyou** [vvoovv/blender-osm#34]
Hello there,

I am new to blender and I'm trying to enable my osm add-on.I get this message every time:
![screenshot from 2016-11-28 01-21-55](https://cloud.githubusercontent.com/assets/22749142/20652791/1be8a4ce-b509-11e6-9c73-99b6023c850f.png)

Any ideas?

**Comment by vvoovv** [comment]
Hello!

I noticed you have two entries (two boxes) for the addon. Could you please delete both of them by pressing remove. And then try to install the addon again.

**Comment by vvoovv** [comment]
I notices through the error overlay, that the checkbox in the lower addon box is checked. That means the addon is enabled. You probably tried to install the addon twice.

Anyway, please delete both addons and try to install the addon again to ensure that everything works fine.

**Comment by Punchyou** [comment]
Good afternoon Vladimir,

The first add-on was the free 2d osm add-on and the second was the 3d one.
Anyway, I deleted both of them and installed only the 3d again as you
suggested. Of course it worked perfectly!

Thanks so much for your time, I appreciate it!

Have a nice evening, greetings from Greece.
M.P.

2016-11-28 15:37 GMT+02:00 Vladimir Elistratov <notifications@github.com>:

**Comment by vvoovv** [comment]
You are welcome and thank you for buying the addon!
