### ISSUE TITLE
Cannot install on Blender 2.73

### ISSUE THREAD

**Issue by douglasfchan** [vvoovv/blender-osm#35]
For some reasons, I must use Blender 2.73. I try to install your zip folder of paid version-'blender-osm' by install from File of User Preferences many times. But still fail. I have followed your installation instruction.
![installation problem of openstreetmap addon](https://cloud.githubusercontent.com/assets/24227219/20672013/b1a845b2-b5ba-11e6-8659-87a21c2ec82b.png)

Please help!

**Comment by douglasfchan** [comment]
When I Enable an addon. The Error Report is as followings:
![error report](https://cloud.githubusercontent.com/assets/24227219/20672692/1e826314-b5bd-11e6-92e9-299b89fc5e1a.png)

**Comment by vvoovv** [comment]
The addon uses the module _mathutils.bvhtree_ which appeared in Blender 2.78.

Please try to use Blender 2.78.

It's also possible to used multiple versions of Blender at once. You could use 2.78 to import an OSM file, save it and open in 2.73. [Here](http://blender.stackexchange.com/questions/28879/how-well-does-blender-handle-multiple-instalations-side-by-side) is described how to use multiple Blender versions.

**Comment by douglasfchan** [comment]
Thanks a lot! After installation of Blender 2.78 on the same computer, I can install the OpenStreetMap.osm  file.

**Comment by vvoovv** [comment]
You are welcome and thank you for buying the addon!
