### ISSUE TITLE
still asking me for buy osm street map

### ISSUE THREAD

**Issue by divyadity7** [vvoovv/blender-osm#36]
Dear sir..
i just buy osm addons from https://gumroad.com but i'm still facing the same problem... osm addons says buy for 3D use..
i have purchase file how to install this file tell me fast..

**Comment by vvoovv** [comment]
Hello!

Please send the date of the purchase and the e-mail address you used for the purchase to this [address](prokitektura+support@gmail.com), so I can check.

Please try to delete the previous version of the addon before downloading the purchased version:

 * _File → User Preferences... → Addons_
 * Type _osm_ in the search box in the top left corner of the _Addons_ tab to find the addon
 * Press _Remove_ button in the GUI box with the header _Import-Export: Import OpenStreetMap (.osm)_

**Comment by divyadity7** [comment]
purchase date is 20/12/2016
