### ISSUE TITLE
About the payment

### ISSUE THREAD

**Issue by a5006** [vvoovv/blender-osm#37]
Hi,sir,
I am really interest in your addon, and i do want to pay for it , but the ploblem is that  I am in China, so it is not easy for me to pay this by Paypal ,we often use Alipay for purchase in internet, so ,I want to know if you have Alipay account that I can pay to you.

**Comment by vvoovv** [comment]
I'd like to reply your privately, because it's payment related problem.

Please copy your message to this [address](mailto:prokitektura+support@gmail.com)

**Comment by a5006** [comment]
I had sent to you ,pls check it in your email box. Thanks again.

**Comment by vvoovv** [comment]
Thank you, I sent you a reply via e-mail

**Comment by a5006** [comment]
very nice!! I had finished to pay and download it. I like this addon ,by the way ,I know this addon from a Forum called ZHIHU. there is a boy write a Tutorial of C4D ,and he talked about this.
here is the link: <a href="https://zhuanlan.zhihu.com/p/22048858?refer=lowpoly">link</a>

**Comment by vvoovv** [comment]
Thank you for buying the addon and for the link!

Do you work with Blender or C4D?

**Comment by a5006** [comment]
Yes, I am a designer and coder, I like the cool thing.

**Comment by vvoovv** [comment]
Thank for the reply!

By the way, You've got a nice userpic :)

**Comment by a5006** [comment]
Thanks
