### ISSUE TITLE
still asking for purchase

### ISSUE THREAD

**Issue by divyadity7** [vvoovv/blender-osm#38]
help me sir

**Comment by divyadity7** [comment]
which file addons file did attach says try again

**Comment by vvoovv** [comment]
what is your e-mail?

**Comment by vvoovv** [comment]
I need your e-mail you entered for the purchase. You can send it to prokitektura+support@gmail.com

**Comment by vvoovv** [comment]
Did you solve the problem?

If not,
please send a message to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com)
