### ISSUE TITLE
Building with roof:type=gabled not displaying

### ISSUE THREAD

**Issue by crschmidt** [vvoovv/blender-osm#39]
Hi!

I'm new to the Simple3DBuildings spec for OSM, so if this is wrong, please feel free to let me know.

I'm attempting to model my house, which is a simple two-part: One part with two levels, one part with one level. 

Initially, I simply added two additional ways with a building:part=yes tag; I then added a relation (in a local file, not uploaded to OSM) which attempts to collect them; neither appears to be displaying in Blender.

I've attached an XML file which I'm loading, and would be curious if you have any thoughts on why it might not be working.

I do see that according to the console, it is parsing the building:
Parsing OSM file: 0:00:00.000639
The number of buildings: 1
Processing of parsed OSM data: 0:00:00.000101
Mesh creation in Blender: 0:00:00.000993
Total duration: 0:00:00.001845

And if I remove the building:part <way>s, then it is correctly displaying (but without the multi-level heights, obviously).

Not sure if this is a modelling problem in my OSM, or a tool problem.

Thanks!

[myhouse-2.osm.txt](https://github.com/vvoovv/blender-osm/files/670909/myhouse-2.osm.txt)

**Comment by crschmidt** [comment]
Okay, this looks like it's a problem with roof:type='gabled' not displaying for me. If I remove the roof:type, things work fine.

**Comment by vvoovv** [comment]
Works with  the released version.

**Comment by vvoovv** [comment]
However, _roof:type=gabled_ isn't supported in the release version, It's treated as a flat roof in the release version,

**Comment by crschmidt** [comment]
I'm working directly from the dev branch of git; if that's not intended to work, then feel free to close this ticket :) Thanks!

**Comment by vvoovv** [comment]
Try setting roof:height=2 for both building parts, in order to work in the dev branch.

**Comment by vvoovv** [comment]
I set to much (10 meters) for the default height of a gabled roof. So the roof becomes larger than the total height of a building part with the roof. And the importer consider the roof part in question as invalid.

**Comment by vvoovv** [comment]
Here is what I have with roof:height=2 for both building parts:
![gabled](https://cloud.githubusercontent.com/assets/613295/21457768/c6f337b0-c942-11e6-976e-193e8d7fcff1.png)
The roof toop is under development

**Comment by crschmidt** [comment]
Yep, I see that now :) My bad! I actually pulled from git earlier this morning, in a version that wasn't as done; now that I've pulled again, I see it's working better, though the roof top could use a bit more "top" :) SInce this is still under development, I'll close this out and let you actually work on it rather than bothering you :) Thanks!

**Comment by vvoovv** [comment]
By the way, you don't need to create a relation of the _type=building_. A building outline tagged with _building=yes_ and encompassing both building parts is enough.

We also have a forum to discuss 3D in OSM: https://forum.openstreetmap.org/viewforum.php?id=42
Use your OSM account and password to log in.
