### ISSUE TITLE
"blender-osm" licensed under GNU GPL (according Blender rules)

### ISSUE THREAD

**Issue by Symbian9** [vvoovv/blender-osm#42]
I previously got "blender-geo" (while it was in opensource state), where was only one limitation:
```
# This is the release version of the plugin file io_import_scene_osm_dev.py
# If you would like to make edits, make them in the file io_import_scene_osm_dev.py and other related modules
# To create the release version of io_import_scene_osm_dev.py execute:
# python plugin_builder.py io_import_scene_osm_dev.py
```

It had not any copyright restrictions or limitations for forking. So, how I could fork it? Under MIT or so?

**Comment by vvoovv** [comment]
It's pure technical issue, it has nothing to do with license.
All Blender addons must have GNU GPL license according to https://www.blender.org/support/faq/:
_If you share or publish Python scripts – if they use the Blender API calls – have to be made available compliant to the GNU GPL as well._

**Comment by Symbian9** [comment]
@vvoovv, So, this mean, that ALL addons if they atleast include string <code>import bpy</code> must be licensed under GPL, right?

**Comment by vvoovv** [comment]
Yes, I think so.

**Comment by Symbian9** [comment]
> Yes, I think so

Why you not describe it in current "blender-osm" addon code?

**Comment by vvoovv** [comment]
I forgot to include the license file. The next public release will have it.
Thanks for the reminder.

**Comment by Symbian9** [comment]
> I forgot to include the license file. The next public release will have it. Thanks for the reminder.

Also add this licensing info into main README file.

**Comment by vvoovv** [comment]
The addon is release under GNU GPL. The attribution will be added in the next release.

Your last statement isn't correct. If you modify software privately,there is no need to provide modifications back.

**Comment by Symbian9** [comment]
> Your last statement isn't correct. If you modify software privately, there is no need to provide modifications back.

Not true. If You use GNU GPL code (Blender API) in you own code, than you CAN'T drop GNU GPL never! (ask FSF for it)

You can not use GNU GPL only for fully scratch code, that not use any 3rd party API.

**Comment by Symbian9** [comment]
@vvoovv, removing "dev" and "old" branches isn't solution: I already forked them and archived according GNU GPL.

Also this topic archived
* http://web.archive.org/web/20170103144355/https://github.com/vvoovv/blender-osm/issues/42

P.S.: maybe it would be usefull for you understand GNU GPL
* https://www.gnu.org/licenses/gpl-faq.html

**Comment by vvoovv** [comment]
Why did you archive this topic?

**Comment by Symbian9** [comment]
> Why did you archive this topic?

For history.

**Comment by vvoovv** [comment]
It will be kept in this repo anyway.

**Comment by Symbian9** [comment]
@vvoovv, And why you remove "dev" & "old" brances?

**Comment by vvoovv** [comment]
The development is done in the repo with limited access. All customers will get full source code under GPL license.

**Comment by Symbian9** [comment]
> All customers will get full source code under GPL license.

And where this "updated" licensing info described?
* http://wiki.openstreetmap.org/wiki/Blender
* https://forum.openstreetmap.org/viewtopic.php?id=25188
* https://github.com/vvoovv/blender-osm/blob/master/README.md

**Comment by vvoovv** [comment]
The distribution contains all necessary information about licensing according to https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by Symbian9** [comment]
As I understand, README.md is part of distribution and it must include this info.

**Comment by vvoovv** [comment]
REAMDE.md is neither source file nor a part of the distribution.

**Comment by vvoovv** [comment]
Added copyright notice and copying permission statement to each source file.
Added GNU GPL text to the the distribution.
Added GNU GPL license in README.md and documentation.

**Comment by ghost** [comment]
Archived
* https://web.archive.org/web/20170111141006/https://github.com/vvoovv/blender-osm/issues/42

**Comment by ghost** [comment]
> Added GNU GPL license in README.md and documentation.

@vvoovv, why are you lying? I can't see this info in README.md
* https://github.com/vvoovv/blender-osm/blob/info/README.md

**Comment by vvoovv** [comment]
Use search function of your browser for the word GPL

**Comment by ghost** [comment]
> All customers will get the addon source code under GPL license!

License is GNU GPL, and you don't show what version of GNU GPL used. Also, whole project on Github must be marked as GNU GPL.

**Comment by FractalizeR** [comment]
There is no project on GitHub now as I can see. The project page now serves advertising purposes only. And this seems to violate GitHub Terms of Service: https://help.github.com/articles/github-terms-of-service/#j-advertising-on-github

> GitHub Repositories

> GitHub repositories are intended to host Content. You may include static images, links, and promotional text in the README documents associated with your repositories, but they must be related to the project you are hosting on GitHub.

> You may not advertise in other Users' repositories, such as by posting monetized or excessive bulk content in issues.

**Comment by vvoovv** [comment]
The project hosts documentation related to the blender-osm addon.
See the documentation pages at https://github.com/vvoovv/blender-osm/wiki

No link is pointing to this github repo.
So I don't see any violation of the GitHub Terms of Service.

**Comment by andreygursky** [comment]
> Also, whole project on Github must be marked as GNU GPL.

@Symbian9, marking is a nice feature to find out quickly what license is in use. But why do you insist on "must"?

There are projects with files under different licenses (and even differently licensed code pieces in a file). It is also possible to compile the same project resulting in different licenses.

**Comment by vvoovv** [comment]
Good news!
All source code is back: https://github.com/vvoovv/blender-osm/tree/release
